server:
  port: 8082

weather:
  api:
    base-url: https://api.weatherapi.com
    key: ea6ac94922bf41b8ad4211249232303

spring:
  application:
    name: weather-service


# JWT Configuration
jwt:
  secret: UHJ1ZWJhdGVjbmljYWp3dHNwcmluZ2Jvb3QxMjM0NTY3ODkwQUJDREVGRw==
  expiration: 3600000 # 1 hora en milisegundos